apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc
parameters:
  type: cloud_ssd
provisioner: fuseim.pri/ifs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
