version: "3" 
services: 
 rabbitmq: 
 image: "rabbitmq" 
 networks: 
 - nameko_net 
 nameko-microservice: 
 build: "./helloservice/" 
 networks: 
 - nameko_net 
 environment: 
 - nameko_username=guest 
 - nameko_password=guest 
 depends_on: 
 - rabbitmq 
 restart: always 
 nameko-app: 
 build: "./my-app/" 
 depends_on: 
 - nameko-microservice 
 ports: 
 - "5000:5000" 
 networks: 
 - nameko_net 
 environment: 
 - nameko_username=guest 
 - nameko_password=guest 
 restart: always 
networks: 
 nameko_net: 
driver: bridge