apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
  name: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
      containers:
      - image: example
      - mountPath: /apps/srv/apm/agent/
        name: pinpoint-agent-volume
      initContainers:
      - command:
        - cp
        - -r
        - /pinpoint-agent-2.1.0
        - /apps/srv/apm/agent/
        image: harbor.dockerstep7.com/libary/pinpoint:2.1.0-init
        imagePullPolicy: IfNotPresent
        name: multi-test-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /apps/srv/apm/agent/
          name: pinpoint-agent-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 85
      volumes:
      - emptyDir: {}
        name: pinpoint-agent-volume
