apiVersion: v1 
kind: Service 
metadata: 
 name: kafka-manager 
 labels: 
 app: kafka-manager 
spec: 
 type: NodePort 
 ports: 
 - name: kafka 
 port: 9000 
 targetPort: 9000 
 nodePort: 30900 
 selector: 
 app: kafka-manager 
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: kafka-manager 
 labels: 
 app: kafka-manager 
spec: 
 replicas: 1 
 selector: 
 matchLabels: 
 app: kafka-manager 
 template: 
 metadata: 
 labels: 
 app: kafka-manager 
 spec: 
 containers: 
 - name: kafka-manager 
 image: zenko/kafka-manager:1.3.3.22 
 imagePullPolicy: IfNotPresent 
 ports: 
 - name: kafka-manager 
containerPort: 9000 
 protocol: TCP 
 env: 
 - name: ZK_HOSTS 
value: "zookeeper:2181" 
livenessProbe: 
 httpGet: 
 path: /api/health 
 port: kafka-manager 
readinessProbe: 
 httpGet: 
 path: /api/health 
 port: kafka-manager 
 resources: 
 limits: 
 cpu: 500m
  memory: 512Mi 
 requests: 
 cpu: 250m 
 memory: 256Mi